### ISSUE TITLE
Profile pages: Issues list not clickable for some contributors

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckhack.com#16]
## Steps to reproduce:
1. Look at the profile page for ankushg07: https://duckduckhack.com/u/ankushg07/
2. Click on "Issues and PRs"

## What should happen:
The list of that contributor's issues and PRs should display.

## What actually happens:
Nothing. Note that for some other contributors the behaviour is fine.

**Comment by russellholt** [comment]
@MariagraziaAlastra ideas?

**Comment by MariagraziaAlastra** [comment]
The right repo for this issue is [community-platform](https://github.com/duckduckgo/community-platform), that's where the DDH profiles pages code lives.

I think it's an issue with the avatar URL not being retrieved for the assignees, but I'd have to verify
