### ISSUE TITLE
C# topic breaks page

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/duckduckhack.com#17]
I noticed only one issue one issues.html.

Saw there was a browser error that said `#C# invalid expression`
Went to fathead issues and saw that this issue was created recently:
https://github.com/duckduckgo/zeroclickinfo-fathead/issues/663

experimented by removing the `Topic: C#` label, and the issues page is back.

Must be a problem with dealing with the `#` in the label.

@MariagraziaAlastra

**Comment by MariagraziaAlastra** [comment]
Fixed in #18

**Comment by moollaza** [comment]
Fixed with recent changes. Temporarily renamed `C#` to `C Sharp`
