### ISSUE TITLE
Implement Updated DuckDuckHack.com Design

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckhack.com#36]
Our design team has prepared an updated design for the DuckDuckHack.com landing page which we need a developer to implement.

Below is spec sheet outlining the design changes that need to be implemented. Attached is a with some of the image assets (the other icons + logo are coming soon!)

**Note**: We have since changed the example image from the Regex Cheat Sheet to the Currency Converter. The updated design should continue to use the Currency Converter image

## Spec:

Whole Page
![ddh-spec-sheet](https://cloud.githubusercontent.com/assets/873785/23969216/03d70604-099c-11e7-9e24-35af58b6c60d.png)

---

Hero Image
![ddh-browser-specs](https://cloud.githubusercontent.com/assets/873785/23969237/1f0d910e-099c-11e7-84bd-01271e8547e4.png)

### Assets:
[DDH-Assets.zip](https://github.com/duckduckgo/duckduckhack.com/files/967916/DDH-Assets.zip)

**Comment by loganom** [comment]
@moollaza It looked like the assets included did not exactly resemble the attached image above. Can you confirm that the assets included are the ones that should be used? 

I'm not familiar with the fonts listed in the mockup.. "ProximaNova-Semibold" - is this included in the project or will I need to request that they be added? (this may be a silly question).

I haven't opened a PR yet, i'm going to wait for responses to these questions. If you want to check out what I have thus far, it is available here: https://github.com/loganom/duckduckhack.com/tree/iss-36

**Comment by moollaza** [comment]
@loganom my apologies, I must have uploaded the wrong folder.

I've updated the assets, it should be good now 👍

**Comment by moollaza** [comment]
> I'm not familiar with the fonts listed in the mockup.. "ProximaNova-Semibold" - is this included in the project or will I need to request that they be added? (this may be a silly question).

I believe Proxima-Nova is available, if it's not just use the current font, I can add that later. I'm more concerned about implementing the icons but visual layout for the call-to-action 👍

**Comment by moollaza** [comment]
@loganom here's the correct assets 👍 

[DDH-CTA-Images.zip](https://github.com/duckduckgo/duckduckhack.com/files/967966/DDH-CTA-Images.zip)

**Comment by loganom** [comment]
Summary of conversation with @moollaza via Slack

- DDH-CTA-Assets contains community / launch svgs, these images have grey backgrounds
- Ensure "semi-bold" text uses font-weight 400 
- Assume "Leading" from mockups is line-height 1.8

**Comment by pjhampton** [comment]
I guess we can close this for now 👍  Thanks everyone
