### ISSUE TITLE
Update Meetup Link in Footer

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckhack.com#38]
We're closing out our pro account, so the new link needs to be: 

https://www.meetup.com/topics/duckduckgo/

**Comment by pjhampton** [comment]
I will deal with this in my small proj.

**Comment by pjhampton** [comment]
Hey @moollaza!

Check out the following...

  - Documentation: This is dealt with https://github.com/duckduckgo/duckduckhack-docs/pull/123/commits/948ac4ac02820017f7083c001bc16727661e31be

  - DuckDuckHack: This is dealt with https://github.com/duckduckgo/duckduckhack.com/commit/a615f3cc4b204d3eada3a7766ab29c5eb9329eb3
