### ISSUE TITLE
Overlapping text on DuckDuckHack.com Homepage when viewed on small viewports...

### ISSUE THREAD

**Issue by busticated** [duckduckgo/duckduckhack.com#47]
Hi :wave:

I noticed this and figured I'd report it. The "Discuss Your Ideas" and "Become a Leader" sections overlap when viewed with a browser with a small viewport (e.g iPhone, Galaxy S5).

![screen shot 2017-08-10 at 4 15 04 pm](https://user-images.githubusercontent.com/367674/29196158-82d2f6ba-7de7-11e7-9588-bbdcd372f5a0.png)

-matt

**Comment by moollaza** [comment]
Thanks for reporting. DuckDuckHack.co has since changed.
