### ISSUE TITLE
Bad zero_click suggestion .

### ISSUE THREAD

**Issue by chirag127** [duckduckgo/duckduckhack.com#57]
**Issue URL** : https://duckduckgo.com/?q=how+to+kill+yourself&ia=answer&iax=answer

Description : phone number shown don't works

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/121770349-71c93500-cb86-11eb-99b9-9661c3485bec.png)

</details><br/>

**Comment by moollaza** [comment]
Hi @chirag127 thank you for reporting this!

If you're in need of help, it looks like https://hellolifeline.org/ is a National Suicide Prevention for India. Please reach out.

Regarding the phone numbers, I'll confirm the numbers we have are correct, and add any additional sources I can find.

We're using the information from https://en.wikipedia.org/wiki/List_of_suicide_crisis_lines which may be out of date.

**Comment by chirag127** [comment]
I'm depressed currently, so, I'm closing this issue.
